//! Locating the ComfyUI entrypoint and turning it into a [`SpawnSpec`]. Kept
//! apart from the adapter's state machine in `mod.rs`.
//!
//! Real ComfyUI is `<venv python> <checkout>/main.py`; the test fixture
//! (`aiwm-fake-comfy`) is a single self-contained executable. [`ComfyLaunch`]
//! covers both — `main` is `None` for the fixture.

use std::ffi::OsString;
use std::fmt::Write as _;
use std::net::Ipv4Addr;
use std::path::{Path, PathBuf};

use super::RUNTIME_ID;
use crate::model::ModelKind;
use crate::runtime::SpawnSpec;
use crate::{CoreError, Result};

/// Env override for the ComfyUI interpreter (or a standalone fixture exe).
pub(super) const PYTHON_ENV: &str = "AIWM_COMFYUI_PYTHON";
/// Env override for the ComfyUI checkout directory (the one holding `main.py`).
pub(super) const DIR_ENV: &str = "AIWM_COMFYUI_DIR";

const PYTHON_EXE: &str = if cfg!(windows) {
    ".venv\\Scripts\\python.exe"
} else {
    ".venv/bin/python"
};

/// How to start the ComfyUI server.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ComfyLaunch {
    /// The interpreter, or a self-contained executable when `main` is `None`.
    pub program: PathBuf,
    /// `main.py` for a real checkout; `None` for the fixture.
    pub main: Option<PathBuf>,
    /// Extra raw arguments, appended verbatim (Settings-configurable flags in
    /// 3.7; the test fixture's `--fake-ready-ms`).
    pub extra_args: Vec<String>,
}

/// The directories ComfyUI is told to use.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ComfyDirs {
    /// `--base-directory` — ComfyUI's `models/`, `input/`, `temp/`.
    pub base: PathBuf,
    /// `--output-directory` — where generated images land.
    pub output: PathBuf,
    /// Root of the canonical model store (`Config::store_path`). ComfyUI is
    /// pointed at its `image/*` subfolders via `extra_model_paths.yaml` (3.3).
    pub models_store: PathBuf,
}

impl ComfyDirs {
    /// Where the generated `extra_model_paths.yaml` lives.
    pub(super) fn model_paths_yaml(&self) -> PathBuf {
        self.base.join("aiwm-model-paths.yaml")
    }

    /// Create the base + output directories and (re)write the model-paths YAML.
    /// Idempotent; called before every server start so a changed store path or
    /// a fresh install is picked up.
    pub(super) fn ensure(&self) -> Result<()> {
        for dir in [&self.base, &self.output] {
            std::fs::create_dir_all(dir).map_err(|e| dir_err(dir, e))?;
        }
        let yaml = self.model_paths_yaml();
        std::fs::write(&yaml, model_paths_yaml_body(&self.models_store))
            .map_err(|e| dir_err(&yaml, e))
    }
}

fn dir_err(path: &Path, e: std::io::Error) -> CoreError {
    CoreError::Runtime {
        runtime: RUNTIME_ID.into(),
        message: format!("comfyui setup: {}: {e}", path.display()),
    }
}

/// The `extra_model_paths.yaml` body: point ComfyUI at `<store>/image/<folder>/`
/// for every image model kind (ADR-019). A junction can't reach the store —
/// it's on a different volume from the ComfyUI install — but this config can.
fn model_paths_yaml_body(store_root: &Path) -> String {
    let base = store_root
        .join("image")
        .to_string_lossy()
        .replace('\\', "/");
    let mut yaml = String::from(
        "# Generated by AI Workstation Manager — do not edit; it is rewritten on each launch.\naiwm:\n",
    );
    let _ = writeln!(yaml, "  base_path: {base}");
    for kind in ModelKind::IMAGE_KINDS {
        let Some(folder) = kind.comfy_folder() else {
            continue;
        };
        let sub = kind.store_subdir().trim_start_matches("image/");
        let _ = writeln!(yaml, "  {folder}: {sub}/");
    }
    yaml
}

/// Build the launch command. Always pins `--listen 127.0.0.1` (ADR-008) and
/// keeps ComfyUI headless + quiet.
pub(super) fn build_spawn_spec(launch: &ComfyLaunch, port: u16, dirs: &ComfyDirs) -> SpawnSpec {
    let mut spec = SpawnSpec::new(&launch.program);
    if let Some(main) = &launch.main {
        spec = spec.arg(main.to_string_lossy().into_owned());
        if let Some(parent) = main.parent() {
            spec.cwd = Some(parent.to_path_buf());
        }
    }
    spec = spec
        .arg("--listen")
        .arg(Ipv4Addr::LOCALHOST.to_string())
        .arg("--port")
        .arg(port.to_string())
        .arg("--base-directory")
        .arg(dirs.base.to_string_lossy().into_owned())
        .arg("--output-directory")
        .arg(dirs.output.to_string_lossy().into_owned())
        .arg("--extra-model-paths-config")
        .arg(dirs.model_paths_yaml().to_string_lossy().into_owned())
        .arg("--disable-auto-launch")
        .arg("--dont-print-server");
    for extra in &launch.extra_args {
        spec = spec.arg(extra.clone());
    }
    spec
}

/// Resolve how to launch ComfyUI: `AIWM_COMFYUI_PYTHON` (+ optional
/// `AIWM_COMFYUI_DIR`), then a managed install under
/// `<runtimes_dir>/comfyui/<version>/`. `lookup` reads env vars (injected for
/// tests). `None` when nothing is installed.
pub(super) fn resolve_launch(
    runtimes_dir: &Path,
    lookup: impl Fn(&str) -> Option<OsString>,
) -> Option<ComfyLaunch> {
    if let Some(raw) = lookup(PYTHON_ENV).filter(|s| !s.is_empty()) {
        let program = PathBuf::from(raw);
        if program.is_file() {
            let main = lookup(DIR_ENV)
                .filter(|s| !s.is_empty())
                .map(|d| PathBuf::from(d).join("main.py"))
                .filter(|p| p.is_file());
            return Some(ComfyLaunch {
                program,
                main,
                extra_args: Vec::new(),
            });
        }
    }

    // Managed: <runtimes_dir>/comfyui/<version>/main.py + .venv python.
    let managed_root = runtimes_dir.join(RUNTIME_ID);
    let entries = std::fs::read_dir(&managed_root).ok()?;
    for entry in entries.flatten() {
        if !entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            continue;
        }
        let dir = entry.path();
        let main = dir.join("main.py");
        let python = dir.join(PYTHON_EXE);
        if main.is_file() && python.is_file() {
            return Some(ComfyLaunch {
                program: python,
                main: Some(main),
                extra_args: Vec::new(),
            });
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dirs() -> ComfyDirs {
        ComfyDirs {
            base: PathBuf::from("C:\\aiwm\\comfyui-data"),
            output: PathBuf::from("C:\\aiwm\\outputs"),
            models_store: PathBuf::from("E:\\AI\\models"),
        }
    }

    #[test]
    fn model_paths_yaml_maps_every_image_kind_to_a_comfy_folder() {
        let body = model_paths_yaml_body(Path::new("E:\\AI\\models"));
        assert!(body.contains("base_path: E:/AI/models/image"));
        assert!(body.contains("checkpoints: checkpoints/"));
        assert!(body.contains("diffusion_models: diffusion_models/"));
        assert!(body.contains("vae: vae/"));
        assert!(body.contains("loras: loras/"));
        assert!(body.contains("text_encoders: text_encoders/"));
    }

    #[test]
    fn ensure_writes_the_yaml_and_makes_the_dirs() {
        let tmp = tempfile::tempdir().unwrap();
        let d = ComfyDirs {
            base: tmp.path().join("data"),
            output: tmp.path().join("out"),
            models_store: tmp.path().join("store"),
        };
        d.ensure().unwrap();
        assert!(d.base.is_dir() && d.output.is_dir());
        let yaml = std::fs::read_to_string(d.model_paths_yaml()).unwrap();
        assert!(yaml.contains("base_path:") && yaml.contains("checkpoints:"));
        d.ensure().unwrap(); // idempotent
    }

    #[test]
    fn spawn_spec_for_a_real_checkout_runs_python_with_main_and_flags() {
        let launch = ComfyLaunch {
            program: PathBuf::from("C:\\c\\.venv\\Scripts\\python.exe"),
            main: Some(PathBuf::from("C:\\c\\ComfyUI\\main.py")),
            extra_args: vec!["--lowvram".into()],
        };
        let spec = build_spawn_spec(&launch, 48311, &dirs());
        assert_eq!(spec.program, launch.program);
        assert_eq!(spec.cwd, Some(PathBuf::from("C:\\c\\ComfyUI")));
        let joined = spec.args.join(" ");
        assert!(joined.starts_with("C:\\c\\ComfyUI\\main.py"));
        assert!(joined.contains("--listen 127.0.0.1"));
        assert!(joined.contains("--port 48311"));
        assert!(joined.contains("--base-directory C:\\aiwm\\comfyui-data"));
        assert!(joined.contains("--output-directory C:\\aiwm\\outputs"));
        assert!(joined
            .contains("--extra-model-paths-config C:\\aiwm\\comfyui-data\\aiwm-model-paths.yaml"));
        assert!(joined.contains("--disable-auto-launch"));
        assert!(joined.contains("--dont-print-server"));
        assert!(
            joined.ends_with("--lowvram"),
            "extra args come last: {joined}"
        );
    }

    #[test]
    fn spawn_spec_for_the_fixture_has_no_main_arg() {
        let launch = ComfyLaunch {
            program: PathBuf::from("aiwm-fake-comfy.exe"),
            ..ComfyLaunch::default()
        };
        let spec = build_spawn_spec(&launch, 1, &dirs());
        assert!(spec.cwd.is_none());
        assert!(!spec.args.iter().any(|a| a.ends_with("main.py")));
        assert!(spec.args.join(" ").contains("--port 1"));
    }

    #[test]
    fn resolve_prefers_python_env_and_pairs_it_with_a_dir() {
        let tmp = tempfile::tempdir().unwrap();
        let python = tmp.path().join("python.exe");
        std::fs::write(&python, b"x").unwrap();
        let comfy = tmp.path().join("ComfyUI");
        std::fs::create_dir_all(&comfy).unwrap();
        std::fs::write(comfy.join("main.py"), b"x").unwrap();

        let got = resolve_launch(Path::new("Z:\\nope"), |k| match k {
            PYTHON_ENV => Some(python.clone().into()),
            DIR_ENV => Some(comfy.clone().into()),
            _ => None,
        })
        .unwrap();
        assert_eq!(got.program, python);
        assert_eq!(got.main, Some(comfy.join("main.py")));
    }

    #[test]
    fn resolve_allows_a_standalone_exe_without_a_dir() {
        let tmp = tempfile::tempdir().unwrap();
        let exe = tmp.path().join("fake-comfy.exe");
        std::fs::write(&exe, b"x").unwrap();

        let got = resolve_launch(Path::new("Z:\\nope"), |k| {
            (k == PYTHON_ENV).then(|| exe.clone().into())
        })
        .unwrap();
        assert_eq!(got.program, exe);
        assert_eq!(got.main, None);
    }

    #[test]
    fn resolve_finds_a_managed_install() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join(RUNTIME_ID).join("0.34.0");
        std::fs::create_dir_all(dir.join(".venv").join(if cfg!(windows) {
            "Scripts"
        } else {
            "bin"
        }))
        .unwrap();
        std::fs::write(dir.join("main.py"), b"x").unwrap();
        std::fs::write(dir.join(PYTHON_EXE), b"x").unwrap();

        let got = resolve_launch(tmp.path(), |_| None).unwrap();
        assert_eq!(got.main, Some(dir.join("main.py")));
    }

    #[test]
    fn resolve_is_none_when_nothing_is_installed() {
        let tmp = tempfile::tempdir().unwrap();
        assert_eq!(resolve_launch(tmp.path(), |_| None), None);
    }
}
